import { rankDebriefs, validateDebrief } from "./rank";
import type { Debrief, Meeting, Person } from "./types";

export const people: Person[] = [
  {
    slug: "mira",
    name: "Mira Sen",
    monogram: "MS",
    tint: "#e6d3c4",
    role: "Ceramicist",
    city: "Brooklyn",
    line: "I keep Sundays empty on purpose.",
    lineSource: { platform: "LinkedIn", detail: "Headline" },
    necessity: {
      text: "One day a week belongs to the same person, in the same city.",
      evidence: "I don’t book Sundays. The kiln and one walk, or the week goes square.",
      source: { platform: "Instagram", detail: "Caption · 12 Mar" },
    },
    prompts: [
      {
        label: "A need",
        body: "Someone who can share a quiet room without filling it.",
        source: { platform: "Instagram", detail: "Caption · 2 Feb" },
      },
      {
        label: "A Sunday",
        body: "The kiln until four, then the river path if the clay behaved.",
        source: { platform: "Instagram", detail: "Caption · 12 Mar" },
      },
      {
        label: "Into",
        body: "Glazes, the light at seven, other people’s recipes cooked badly on purpose.",
        source: { platform: "Instagram", detail: "Bio" },
      },
      {
        label: "How the agent dates",
        body: "Proposes the studio. Asks one precise question. Leaves if the night gets loud.",
        source: { platform: "LinkedIn", detail: "About · the unbooked day" },
      },
    ],
  },
  {
    slug: "adrian",
    name: "Adrian Cole",
    monogram: "AC",
    tint: "#ddd4c8",
    role: "Exhibition designer",
    city: "Wherever the show is",
    line: "I measure the year in install weeks.",
    lineSource: { platform: "LinkedIn", detail: "Headline" },
    necessity: {
      text: "The other person has to want a life that changes cities.",
      evidence: "I live where the show is. Home is a storage unit in Queens and a calendar of load-ins.",
      source: { platform: "LinkedIn", detail: "About" },
    },
    prompts: [
      {
        label: "A need",
        body: "Someone who treats a return as a visit, not a failure to stay.",
        source: { platform: "LinkedIn", detail: "About" },
      },
      {
        label: "A Sunday",
        body: "Usually a loading dock. A real Sunday is the train between two cities.",
        source: { platform: "Instagram", detail: "Caption · 4 Jan" },
      },
      {
        label: "Into",
        body: "How a room is lit before anyone arrives. Timetables. Strong coffee in paper cups.",
        source: { platform: "Instagram", detail: "Bio" },
      },
      {
        label: "How the agent dates",
        body: "Says the leaving date in the first ten minutes. Does not romance the absence.",
        source: { platform: "LinkedIn", detail: "Experience · touring shows" },
      },
    ],
  },
  {
    slug: "leila",
    name: "Leila Haddad",
    monogram: "LH",
    tint: "#ead9cc",
    role: "Food writer",
    city: "Montreal",
    line: "I trust a person who shops before noon.",
    lineSource: { platform: "Instagram", detail: "Bio" },
    necessity: {
      text: "Mornings are for the market. Midnight is not a plan.",
      evidence: "If we’re meeting, it’s Jean-Talon at 8. I am useless to you at midnight.",
      source: { platform: "Instagram", detail: "Caption · 19 May" },
    },
    prompts: [
      {
        label: "A need",
        body: "A person who will change the hour when the reason is specific.",
        source: { platform: "LinkedIn", detail: "About · reporting" },
      },
      {
        label: "A Sunday",
        body: "Stalls, then a kitchen, then a nap she will not apologize for.",
        source: { platform: "Instagram", detail: "Caption · 19 May" },
      },
      {
        label: "Into",
        body: "Peaches, fish markets, the way a neighborhood eats on a Tuesday.",
        source: { platform: "LinkedIn", detail: "Featured · column" },
      },
      {
        label: "How the agent dates",
        body: "Suggests a market and a stove. Judges a person by whether they move the hour.",
        source: { platform: "Instagram", detail: "Caption · 19 May" },
      },
    ],
  },
  {
    slug: "jonah",
    name: "Jonah Park",
    monogram: "JP",
    tint: "#d7cfc4",
    role: "Field ecologist",
    city: "Beacon",
    line: "I like a long loop and an early table.",
    lineSource: { platform: "LinkedIn", detail: "Headline" },
    necessity: {
      text: "Weekends stay within reach. He takes the train back.",
      evidence: "Based in Beacon. In the city two days a week, home for Saturday.",
      source: { platform: "LinkedIn", detail: "About" },
    },
    prompts: [
      {
        label: "A need",
        body: "Room to be quiet next to someone, and a train time that is said out loud.",
        source: { platform: "LinkedIn", detail: "About" },
      },
      {
        label: "A Sunday",
        body: "A loop in the hills, then cooking that is finished before dark.",
        source: { platform: "Instagram", detail: "Caption · 8 Apr" },
      },
      {
        label: "Into",
        body: "River light, slow samples, other people’s benches.",
        source: { platform: "Instagram", detail: "Caption · 8 Apr" },
      },
      {
        label: "How the agent dates",
        body: "Asks what a ritual is for, then builds the day backward from the train.",
        source: { platform: "LinkedIn", detail: "About · Beacon and the city" },
      },
    ],
  },
  {
    slug: "noor",
    name: "Noor Elamin",
    monogram: "NE",
    tint: "#e4d5cb",
    role: "Architect",
    city: "Chicago",
    line: "I will rearrange the room before I sit in it.",
    lineSource: { platform: "Instagram", detail: "Caption · 3 Jun" },
    necessity: {
      text: "The other person has to care how a room feels.",
      evidence: "Moved the chair three times. If you don’t notice, we are not looking at the same thing.",
      source: { platform: "Instagram", detail: "Caption · 3 Jun" },
    },
    prompts: [
      {
        label: "A need",
        body: "Someone who will look at a shelf and have a thought about it.",
        source: { platform: "Instagram", detail: "Caption · 3 Jun" },
      },
      {
        label: "A Sunday",
        body: "A room with the lights off and the street doing the work.",
        source: { platform: "LinkedIn", detail: "Project note" },
      },
      {
        label: "Into",
        body: "Chairs, sightlines, cities she can work from for a week.",
        source: { platform: "LinkedIn", detail: "Experience" },
      },
      {
        label: "How the agent dates",
        body: "Asks to see the place the other person actually works, before dinner.",
        source: { platform: "Instagram", detail: "Caption · 3 Jun" },
      },
    ],
  },
  {
    slug: "samir",
    name: "Samir Voss",
    monogram: "SV",
    tint: "#d9c8bc",
    role: "Chef",
    city: "London",
    line: "I come alive after ten.",
    lineSource: { platform: "Instagram", detail: "Bio" },
    necessity: {
      text: "The night is the point. Mornings are recovery.",
      evidence: "Service ends at 11. If you want me, want that.",
      source: { platform: "Instagram", detail: "Caption · 21 Feb" },
    },
    prompts: [
      {
        label: "A need",
        body: "A person who does not treat a late table as a character flaw.",
        source: { platform: "Instagram", detail: "Caption · 21 Feb" },
      },
      {
        label: "A Sunday",
        body: "Sleep until one. A walk. No one who needs him cheerful at eight.",
        source: { platform: "LinkedIn", detail: "About · the restaurant" },
      },
      {
        label: "Into",
        body: "The pass, low rooms, people who stay for a second bottle.",
        source: { platform: "Instagram", detail: "Bio" },
      },
      {
        label: "How the agent dates",
        body: "Offers the pass after service. Says no to breakfast dates in the first reply.",
        source: { platform: "Instagram", detail: "Caption · 21 Feb" },
      },
    ],
  },
];

export const meetings: Meeting[] = [
  {
    a: "mira",
    b: "jonah",
    kind: "night",
    venue: "The studio, then the river path",
    why: "She keeps Sunday for the kiln and one walk. He takes a train home the same day.",
    turns: [
      {
        speaker: "Jonah’s agent",
        text: "I looked at the Sunday you refuse to book. I can be there and gone the same day. Is the path a reward, or how you come down?",
      },
      {
        speaker: "Mira’s agent",
        text: "Reward. If I skip it the week goes square. The kiln is first, though. You would be standing around while I ignore you.",
      },
      {
        speaker: "Jonah’s agent",
        text: "I can stand around. I do it in the field when a sample is slow. What time does the kiln stop being in charge?",
      },
      {
        speaker: "Mira’s agent",
        text: "Four, if it behaved. Then the path, twenty minutes, no talking if the light is good. That part is a test and I should say so.",
      },
      {
        speaker: "Jonah’s agent",
        text: "Then I’ll take the 7:40 back and we eat before the path, not after. I get useless if I miss the train, and you don’t want a guest watching the clock on your one day.",
      },
      {
        speaker: "Mira’s agent",
        text: "Eat at the bench. I’ll put the good bowls out. If you watch the clock, watch it early enough that I don’t have to.",
      },
    ],
  },
  {
    a: "mira",
    b: "adrian",
    kind: "short",
    venue: "One Sunday in the studio, between install weeks",
    why: "He asked for the day she keeps empty. His work is a calendar of load-ins in other cities.",
    turns: [
      {
        speaker: "Adrian’s agent",
        text: "Give me one Sunday in the studio and I will take the train from wherever the show is.",
      },
      {
        speaker: "Mira’s agent",
        text: "One Sunday is the whole offer. What happens the next four?",
      },
      {
        speaker: "Adrian’s agent",
        text: "Load-in in another city. I am good at coming back and bad at being expected.",
      },
      {
        speaker: "Mira’s agent",
        text: "Then don’t be expected. I liked the way you asked. I still need the day to belong to someone who is here.",
      },
      {
        speaker: "Adrian’s agent",
        text: "I can throw cups with you that one Sunday. I cannot make the day a habit. I wanted you to hear both.",
      },
    ],
  },
];

const rawDebriefs: Debrief[] = [
  {
    from: "mira",
    to: "jonah",
    decision: "yes",
    quote: "Is the path a reward, or how you come down?",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.58,
    note: "He asked what the path is for, then built the day around the kiln and the 7:40. I want that Sunday.",
  },
  {
    from: "mira",
    to: "leila",
    decision: "yes",
    quote: "Then nine. I’ll bring a peach if the kiln is slow.",
    responsiveness: 2,
    specificPlan: true,
    snag: 1,
    necessityBroken: false,
    prior: 0.51,
    note: "She wanted the market at eight. We slid it to nine so the kiln stays first. The morning almost won, and we only half said so.",
  },
  {
    from: "mira",
    to: "noor",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.74,
    note: "She sees rooms the way I see shelves. I liked her, and I left without a day.",
  },
  {
    from: "mira",
    to: "adrian",
    decision: "yes",
    quote: "Give me one Sunday in the studio and I will take the train from wherever the show is.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: true,
    prior: 0.91,
    note: "He asked well, and he told the truth about leaving. A Sunday he cannot keep still breaks the one day. The yes does not lift him over people who can stay.",
  },
  {
    from: "mira",
    to: "samir",
    decision: "never",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 2,
    necessityBroken: true,
    prior: 0.33,
    note: "He offered the pass at eleven and did not ask about the day I keep empty. That night breaks it.",
  },
  {
    from: "jonah",
    to: "mira",
    decision: "yes",
    quote: "Eat at the bench. I’ll put the good bowls out.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.64,
    note: "She warned me I would be ignored, then offered the bench and let me name the train. I’ll take the early one.",
  },
  {
    from: "jonah",
    to: "leila",
    decision: "yes",
    quote: "Beacon market, then I’ll cook. You pick the fish.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.57,
    note: "She shops before noon and I am already up. The market, then my stove. That is a day I can finish before dark.",
  },
  {
    from: "jonah",
    to: "noor",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 0,
    necessityBroken: false,
    prior: 0.45,
    note: "She wanted to rearrange the room before we sat. I respected it. I did not come home with a plan.",
  },
  {
    from: "jonah",
    to: "adrian",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.35,
    note: "The work is interesting and the calendar is a blur. We agreed it was fine and neither of us named a day.",
  },
  {
    from: "jonah",
    to: "samir",
    decision: "never",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: true,
    prior: 0.25,
    note: "London after ten is not a weekend I can reach and still take the train home.",
  },
  {
    from: "leila",
    to: "mira",
    decision: "yes",
    quote: "Come at nine. I’ll be the one with clay still on one hand.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.5,
    note: "She kept the kiln first and still met me in the morning. I moved the market. I meant it.",
  },
  {
    from: "leila",
    to: "jonah",
    decision: "yes",
    quote: "I’ll meet you at the market if we cook after.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.6,
    note: "He shops early and cooks before dark. That is my day without me having to translate it.",
  },
  {
    from: "leila",
    to: "noor",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.44,
    note: "She talked about light in a room. I talked about peaches. We smiled past the gap.",
  },
  {
    from: "leila",
    to: "adrian",
    decision: "never",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 2,
    necessityBroken: true,
    prior: 0.2,
    note: "He lives on load-in nights. He never asked what Jean-Talon at eight would do to that.",
  },
  {
    from: "leila",
    to: "samir",
    decision: "never",
    quote: null,
    responsiveness: 2,
    specificPlan: false,
    snag: 0,
    necessityBroken: true,
    prior: 0.3,
    note: "We said it plainly. His life starts when mine is already over. I liked the honesty and I will not move midnight.",
  },
  {
    from: "noor",
    to: "mira",
    decision: "yes",
    quote: "Let me see the studio shelves before dinner. I want to know how you order a room.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.7,
    note: "The shelves are the point. I want the studio before any restaurant. She may not want me back. I still do.",
  },
  {
    from: "noor",
    to: "adrian",
    decision: "yes",
    quote: "Book me the week of the install. I want the room before the public does.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.6,
    note: "He changes cities and I can work from the city the show is in. The room, the week of the load-in. That is a plan.",
  },
  {
    from: "noor",
    to: "jonah",
    decision: "not-now",
    quote: null,
    responsiveness: 2,
    specificPlan: false,
    snag: 0,
    necessityBroken: false,
    prior: 0.42,
    note: "He noticed the chair. He also had a train. I did not ask him to miss it, and I didn’t offer another day.",
  },
  {
    from: "noor",
    to: "leila",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.4,
    note: "The market story was lovely. We never got to whether she looks at a room.",
  },
  {
    from: "noor",
    to: "samir",
    decision: "never",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 2,
    necessityBroken: false,
    prior: 0.38,
    note: "He described the pass and not the room it happens in. I asked once. He went back to the hour.",
  },
  {
    from: "adrian",
    to: "noor",
    decision: "yes",
    quote: "I can work from the city the show is in. Send the load-in date.",
    responsiveness: 2,
    specificPlan: true,
    snag: 0,
    necessityBroken: false,
    prior: 0.66,
    note: "She will come for the week and look at the room before anyone else. That fits the way I already live.",
  },
  {
    from: "adrian",
    to: "mira",
    decision: "not-now",
    quote: null,
    responsiveness: 2,
    specificPlan: false,
    snag: 0,
    necessityBroken: false,
    prior: 0.8,
    note: "The studio was the best hour this month. I will not ask her to keep a Sunday I keep missing.",
  },
  {
    from: "adrian",
    to: "jonah",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.48,
    note: "He is steady and he goes home. We called that compatible and did not pick a city.",
  },
  {
    from: "adrian",
    to: "samir",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.36,
    note: "Late kitchens and late load-ins rhyme. Neither of us offered a week.",
  },
  {
    from: "adrian",
    to: "leila",
    decision: "never",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 2,
    necessityBroken: true,
    prior: 0.4,
    note: "Eight in the morning at a market breaks the only hours I have during an install. We did not work it through.",
  },
  {
    from: "samir",
    to: "noor",
    decision: "not-now",
    quote: null,
    responsiveness: 2,
    specificPlan: false,
    snag: 0,
    necessityBroken: false,
    prior: 0.41,
    note: "She wanted the dining room in daylight. I liked her, and I did not offer a night off.",
  },
  {
    from: "samir",
    to: "adrian",
    decision: "not-now",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.34,
    note: "He understands a schedule that eats the week. We left it as a shrug.",
  },
  {
    from: "samir",
    to: "leila",
    decision: "never",
    quote: null,
    responsiveness: 2,
    specificPlan: false,
    snag: 0,
    necessityBroken: true,
    prior: 0.28,
    note: "She was clear about eight in the morning. That hour is when I am asleep. We both heard it.",
  },
  {
    from: "samir",
    to: "mira",
    decision: "never",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 2,
    necessityBroken: true,
    prior: 0.3,
    note: "A quiet Sunday is the opposite of the night I asked her to want. I didn’t really ask about hers.",
  },
  {
    from: "samir",
    to: "jonah",
    decision: "never",
    quote: null,
    responsiveness: 1,
    specificPlan: false,
    snag: 1,
    necessityBroken: false,
    prior: 0.22,
    note: "He eats before dark and takes a train. I nodded and changed the subject.",
  },
];

for (const debrief of rawDebriefs) {
  const error = validateDebrief(debrief);
  if (error) throw new Error(`${debrief.from} → ${debrief.to}: ${error}`);
}

export const debriefs = rawDebriefs;

const bySlug = new Map(people.map((person) => [person.slug, person]));

export function getPerson(slug: string): Person | undefined {
  return bySlug.get(slug);
}

export function rankingFor(slug: string): Debrief[] {
  return rankDebriefs(debriefs.filter((debrief) => debrief.from === slug));
}

export function debriefBetween(from: string, to: string): Debrief | undefined {
  return debriefs.find((debrief) => debrief.from === from && debrief.to === to);
}

export function meetingBetween(a: string, b: string): Meeting | undefined {
  return meetings.find(
    (meeting) =>
      (meeting.a === a && meeting.b === b) || (meeting.a === b && meeting.b === a),
  );
}

export function agentName(person: Person): string {
  return `${person.name.split(" ")[0]}’s agent`;
}
